services:
  postgres:
    image: postgres
    container_name: postgres-controla
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres-controla
    ports:
      - "5434:5432"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres-controla"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend: 
    container_name: backend-controla
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - postgres-network
    depends_on:
      - postgres
    entrypoint: >
      sh -c "
        until nc -z postgres 5432; do
          echo 'Waiting for Postgres...';
          sleep 1;
        done;
        npx prisma migrate deploy;
        node dist/src/server.js;
      "

networks:
  postgres-network:
    driver: bridge
