services:
  postgres:
    image: postgres
    container_name: postgres-controla
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres-controla
    ports:
      - "5434:5432"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres-controla"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  postgres-network:
    driver: bridge
